# Generated by Django 3.0.2 on 2020-01-05 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleBoardComputer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_since', models.DateTimeField(verbose_name='Дата коннекта')),
                ('last_ref', models.DateTimeField(verbose_name='Дата обновления виртуального адреса')),
                ('real_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Реальный адрес')),
                ('virtual_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Виртуальный адрес')),
                ('updated', models.DateTimeField(verbose_name='Дата последнего обновления')),
                ('sbc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbc_monitor.SingleBoardComputer')),
            ],
        ),
    ]
