# Generated by Django 2.2.6 on 2020-01-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleBoardComputer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата подключения/отключения')),
                ('real_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Реальный адрес')),
                ('virtual_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Виртуальный адрес')),
                ('sbc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbc_monitor.SingleBoardComputer')),
            ],
        ),
    ]
