# Generated by Django 2.2.6 on 2020-01-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbc_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleboardcomputer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
